// api/[slug].js - Vercel Serverless Function
export default function handler(req, res) {
  const { slug } = req.query;

  // Link ads chung cho tất cả
  const redirectUrl = "https://broadlyjukeboxunrevised.com/2053781";

  // List ảnh từ ibb
  const images = {
    anh1: "https://i.ibb.co/YBZhBJKg/Gx-Z9-XSxao-AA1-Ups.jpg",
    anh2: "https://i.ibb.co/bMzmDtqK/Gx-Zb-Y87a-QAAX34-N.jpg",
    anh3: "https://i.ibb.co/GfDMgDPN/Gx-Zvihya-QAAMZGg.jpg",
    anh4: "https://i.ibb.co/VYkrzHPW/Gr-Ag-g-EX0-AIb-C2d.jpg",
    anh5: "https://i.ibb.co/mC3SmGK2/Gr-Ai-R7-Ha-AAQQW9x.jpg",
    anh6: "https://i.ibb.co/TQhsLxH/Gr-F3-Ybna-AAA-o-SI.jpg",
    anh7: "https://i.ibb.co/4nxTyfbv/Gu-Of-GTrag-Akg-p.jpg",
    anh8: "https://i.ibb.co/GfcYYTPB/Gu-OYi0-Lag-AQEbpn.jpg",
    anh9: "https://i.ibb.co/35v7CLW3/Gvphc-VXW4-AANIn0.jpg",
    anh10: "https://i.ibb.co/Lh8wH5pz/Gvph-L8i-X0-AAJLZT.jpg",
    anh11: "https://i.ibb.co/wZ4PJB7y/Gvph-OI9-WYAE5-Cd6.jpg",
    anh12: "https://i.ibb.co/dwpd5gKR/Gvph-QYpbs-AIJ1-Zr.jpg",
    anh13: "https://i.ibb.co/zHnHfjGJ/Gvph-Sr-TWIAAtz-Gh.jpg",
    anh14: "https://i.ibb.co/NzZxvQH/Gvph-VDr-W0-AAo-Xpb.jpg",
    anh15: "https://i.ibb.co/KcSNf515/Gvph-Xsi-Xw-AADuvk.jpg",
    anh16: "https://i.ibb.co/Ldyc5XGF/Gvph-Z90a8-AAAccl.jpg",
    anh17: "https://i.ibb.co/k6s2YVWB/Gw-y-WLzb-AAABRHr.png",
    anh18: "https://i.ibb.co/wFzGDsBx/Gw3d-MVFa-EAAz-Ts-X.jpg",
    anh19: "https://i.ibb.co/YTNMnxSQ/Gw9-FE6ib-UAAj5c-I.jpg",
    anh20: "https://i.ibb.co/5XTwX8Kb/Gw-Xpe-PXXw-AAGs-I7.png",
    anh21: "https://i.ibb.co/s9zsYyNp/Gx-S1q-Gbs-AAJs-u.jpg",
    anh22: "https://i.ibb.co/fGSYX1QJ/Gx0-Ug-Aza-EAA0-QQE.jpg",
    anh23: "https://i.ibb.co/9H8vJgBY/Gx0w3lubc-AAAOr-F.jpg",
    anh24: "https://i.ibb.co/vvHZpwNm/Gx1-E4x-Nbc-AAjn1-C.jpg",
    anh25: "https://i.ibb.co/TDZxdPty/Gx18f-HCbo-AAH3-Pp.jpg",
    anh26: "https://i.ibb.co/Zp8C0m0s/Gx-AGkdea4-AAEg-X9.jpg",
    anh27: "https://i.ibb.co/zW47Lbwr/Gxb7z-HGag-AAl-F3-Y.jpg",
    anh28: "https://i.ibb.co/p6FVZhkW/Gxb9-Vlpak-AEu-Uon.jpg",
    anh29: "https://i.ibb.co/HR1Q995/Gxbfo-waw-AAj-DDx.jpg",
    anh30: "https://i.ibb.co/Z6szfm0T/Gxb-IP2b-XQAALb-b.jpg",
    anh31: "https://i.ibb.co/tMbfRmZH/Gxbq-QE-aw-AABMD.jpg",
    anh32: "https://i.ibb.co/RTGNwwGn/Gxcb4-Dub-QAA6-O7-Y.jpg",
    anh33: "https://i.ibb.co/FbB4JNhq/Gxc-Dv-V9a-IAEERsl.jpg",
    anh34: "https://i.ibb.co/35PYTvXq/Gxci-Zz-b-QAAs-KXW.jpg",
    anh35: "https://i.ibb.co/WpWbzs4Q/Gxcjt6-Mb-IAAFIJ.jpg",
    anh36: "https://i.ibb.co/jk97L1Gx/Gx-Ck-D0-Cb-UAMP5fs.jpg",
    anh37: "https://i.ibb.co/4g4FBZfw/Gx-Cm-Iw-Db-UAIWXf-1.jpg",
    anh38: "https://i.ibb.co/QFymBrkc/Gx-Cm-Iw-Db-UAIWXf.jpg",
    anh39: "https://i.ibb.co/0j0rWnm8/Gxc-Oyu-Ob-UAEFVIj.jpg",
    anh40: "https://i.ibb.co/35Hw4j4m/Gxc-QDw6bs-AEf-RQr.jpg",
    anh41: "https://i.ibb.co/ccWsFxSq/Gxc-TJF-bg-AAXi-Ob.jpg",
    anh42: "https://i.ibb.co/JWL0sxRY/Gxcy2bda-UAAl0c-B.jpg",
    anh43: "https://i.ibb.co/QF7n9G1v/Gxc-ZAHkb-QAAU0z-T.jpg",
    anh44: "https://i.ibb.co/FbB4JNhq/Gxc-Dv-V9a-IAEERsl.jpg",
    anh45: "https://i.ibb.co/Q3N4kyYC/Gxd-By2zb-AAAQw-Mt.jpg",
    anh46: "https://i.ibb.co/fYFxkG8c/Gx-DZOn-Ab-UAIPF6p.jpg",
    anh47: "https://i.ibb.co/pvT97Jgg/Gxe16-PRa0-AAKn8-L.jpg",
    anh48: "https://i.ibb.co/YTPtXsHW/Gxe-D0-Fwb-MAEic-Ry.jpg",
    anh49: "https://i.ibb.co/qLhBz7CM/Gx-Ee0n-Lb-UAI9twb.jpg",
    anh50: "https://i.ibb.co/gb700cyy/Gxe-Nby-Ib-MAA-6a-Y.jpg",
    anh51: "https://i.ibb.co/LzjqjFyY/Gxe-NF1zb-QAARxzm.jpg",
    anh52: "https://i.ibb.co/S4R2G1Bh/Gxeqj-Dnbw-AABd-Zr-1.jpg",
    anh53: "https://i.ibb.co/PvR3Ckpm/Gxeqj-Dnbw-AABd-Zr.jpg",
    anh54: "https://i.ibb.co/XQFkVfb/Gxe-Sm-V-bg-AAKj-N5.jpg",
    anh55: "https://i.ibb.co/DHPYxRDN/Gxfjf-BQa-UAA7-VDW.jpg",
    anh56: "https://i.ibb.co/JF3yhqLy/Gxg7-MXZWs-AA84n-K.jpg",
    anh57: "https://i.ibb.co/pvsQDvk5/Gxg-BWn-KXUAAe-Fi-W.jpg",
    anh58: "https://i.ibb.co/PqCS0Ft/Gxg-Kpk-IXs-AArb-UY.jpg",
    anh59: "https://i.ibb.co/3Y59BNRC/Gx-H0-Ye-Ga-QAEg-Le3.jpg",
    anh60: "https://i.ibb.co/Fb3k1dqr/Gxhes08a-UAAMblt.jpg",
    anh61: "https://i.ibb.co/chb4fVwV/Gxhf3m-Obo-AAe-YY.jpg",
    anh62: "https://i.ibb.co/vxqkyLGw/Gxh-Gr-Cub-MAA6p-PL.jpg",
    anh63: "https://i.ibb.co/5X6YgWJd/Gxh-Hb-KGWMAABa-TS.jpg",
    anh64: "https://i.ibb.co/tMBDSHTW/Gxh-Kv-J3bw-AADv4-M.jpg",
    anh65: "https://i.ibb.co/0Ln5gpD/Gxhl0-Dya4-AALTK7.jpg",
    anh66: "https://i.ibb.co/S4w3HbMn/Gxh-P5z9b-QAIQK8-Q.jpg",
    anh67: "https://i.ibb.co/6cPrXxsx/Gxhq5-HNbg-AA9u1t.jpg",
    anh68: "https://i.ibb.co/wNk6SRLj/Gx-Hs-BSVa-IAEEWMH.jpg",
    anh69: "https://i.ibb.co/7tVMhPHW/Gx-HWDGPa-EAAue-Kl.jpg",
    anh70: "https://i.ibb.co/SLdJykB/Gxhzs-N0as-AAp-Lz-L.jpg",
    anh71: "https://i.ibb.co/XkLHcpFh/Gxic1-S5bo-AA1-Rtz.jpg",
    anh72: "https://i.ibb.co/jPRsYFDH/Gxi-KAe-Mbk-AE6p-Br.jpg",
    anh73: "https://i.ibb.co/zTWm69w6/Gxilw-RVa-UAE9-B4t.jpg",
    anh74: "https://i.ibb.co/BVH531NC/Gxj-I-D9a-EAAv-GAd.jpg",
    anh75: "https://i.ibb.co/60Pf093p/Gxk93wwa8-AATXT.jpg",
    anh76: "https://i.ibb.co/shPxRxy/Gxk-CNv7bc-AARZ9a.jpg",
    anh77: "https://i.ibb.co/d07JT8mv/Gxkfue-Rb-IAASxwx.jpg",
    anh78: "https://i.ibb.co/1GP5CXh7/Gxk-Fza-bk-AAKf-F8-1.jpg",
    anh79: "https://i.ibb.co/whdLF7ct/Gx-KI3d-Zbc-AAYtr-K.jpg",
    anh80: "https://i.ibb.co/d0sYqcCt/Gxkkm5qas-AA3-Q6.jpg",
    anh81: "https://i.ibb.co/XZqMzP5f/Gxkq6xlbw-AAis-XP.jpg",
    anh82: "https://i.ibb.co/DgpF2KdQ/Gxk-RHsba4-AA3-H2-Z.jpg",
    anh83: "https://i.ibb.co/k2sF57T4/Gxl-Mc-Vbo-AA9a-Hm.jpg",
    anh84: "https://i.ibb.co/4gTFBh1t/Gx-L-4ufb-AAAGB90.jpg",
    anh85: "https://i.ibb.co/Xf7KY3bc/Gxl-G2afaw-AAN1a-C.jpg",
    anh86: "https://i.ibb.co/FbhWQNcs/Gx-LM85-a-UAA4o-Tv.jpg",
    anh87: "https://i.ibb.co/Q3zMJR5D/Gxlt-F5ea-YAAXf68.jpg",
    anh88: "https://i.ibb.co/prWsR4jd/Gxluh8-Gbg-AAy-VRt.jpg",
    anh89: "https://i.ibb.co/6Rsb29Ht/Gxm-khuaw-AIj-R61.jpg",
    anh90: "https://i.ibb.co/Wv6mR5h8/Gx-M2u2aak-AAKp-Ut.jpg",
    anh91: "https://i.ibb.co/B2F5yknq/Gx-M2w-Ila-QAEBK61.jpg",
    anh92: "https://i.ibb.co/sdTSRWPy/Gx-M4o-Orbg-AAEKBT.jpg",
    anh93: "https://i.ibb.co/fGr6Yd4B/Gxm4-PB-aw-AMWY3-O.jpg",
    anh94: "https://i.ibb.co/bjHZL3HC/Gxm6-K-Xaw-AMPTj-Z.jpg",
    anh95: "https://i.ibb.co/ynztHQnp/Gxm9h-Deb0-AAp-Edr.jpg",
    anh96: "https://i.ibb.co/SwVxhsQN/Gxm26-Waac-AEN8-K4.jpg",
    anh97: "https://i.ibb.co/fzMSTd3z/Gxmc-UOWa-YAAia7v.jpg",
    anh98: "https://i.ibb.co/QvYhQvgd/Gxmj-EE5aw-AEX-gn.jpg",
    anh99: "https://i.ibb.co/CpRXZH5n/Gxmk-W3-Kaw-AMN1-SB.jpg",
    anh100: "https://i.ibb.co/xZYQSbC/Gxmo-Av-Mbk-AAgad-G.jpg",
    anh101: "https://i.ibb.co/PGQZ1Ytb/Gx-MPel9ao-AA-i-W.jpg",
    anh102: "https://i.ibb.co/Fc9R8Xs/Gxmq3ghaw-AQx-Q-k.jpg",
    anh103: "https://i.ibb.co/TqYhStZw/Gxmq9-GWb-QAA-ECN.jpg",
    anh104: "https://i.ibb.co/d4NGZqCk/Gxmq-JOca-UAA9-HR.jpg",
    anh105: "https://i.ibb.co/ds7GwMxy/Gxmr5w0aw-AIk5-Bn.jpg",
    anh106: "https://i.ibb.co/DHyJxwNb/Gxmrw1-Jaw-AAD4c-Z.jpg",
    anh107: "https://i.ibb.co/gFJ5DxLC/Gxm-SSf-Db-EAAMi-M.jpg",
    anh108: "https://i.ibb.co/cXJC5rG3/Gxmtiwsb-EAAOH0c.jpg",
    anh109: "https://i.ibb.co/jPdWXVTW/Gx-Mt-Xk-Za-EAIEh-T1.jpg",
    anh110: "https://i.ibb.co/jPdWXVTW/Gx-Mt-Xk-Za-EAIEh-T1.jpg",
    anh111: "https://i.ibb.co/MxCNMGMJ/Gxm-U6-Qcb-IAAcob-D.jpg",
    anh112: "https://i.ibb.co/GQGz4tcf/Gxm-Wu6-Ma-AAAI66i.jpg",
    anh113: "https://i.ibb.co/vCqyCQg0/Gxm-XRMFa-UAAb-OVg.jpg",
    anh114: "https://i.ibb.co/5hTTtsVD/Gxm-ZWD0a-MAEGQID.jpg",
    anh115: "https://i.ibb.co/VcmGTJbB/Gxn2-Q7-Gaw-AApk-Tp.jpg",
    anh116: "https://i.ibb.co/VYHqj1cm/Gxn-AN0kaw-AA2-MRw.jpg",
    anh117: "https://i.ibb.co/zhLLYcj5/Gxn-CM0baw-AAUl7w.jpg",
    anh118: "https://i.ibb.co/dwHbDdFx/Gxn-Dfhfaw-AIl-FRS.jpg",
    anh119: "https://i.ibb.co/mLBwNV2/Gxn-ELHta-AAASWH2.jpg",
    anh120: "https://i.ibb.co/rGVrrs8c/Gxn-Fu2-Ybc-AAbcf-C.jpg",
    anh121: "https://i.ibb.co/hxPDhQMH/Gxn-HQfkaw-AMq4-r.jpg",
    anh122: "https://i.ibb.co/C3g6qBy7/Gxn-JH1aaw-AIKJZA.jpg",
    anh123: "https://i.ibb.co/mChZM3Rb/Gxn-LEgab-UAAh-PN.jpg",
    anh124: "https://i.ibb.co/VcFmP3v5/Gx-NVg-Zub-UAAbh23.jpg",
    anh125: "https://i.ibb.co/5X01SmCc/Gxoiu-A7aw-AEWft7.jpg",
    anh126: "https://i.ibb.co/SwpD7sXj/Gxop-Wo-Maw-AI4-WRZ.jpg",
    anh127: "https://i.ibb.co/7xsJ3j2m/Gxou-VCras-AAF4-Ay.jpg",
    anh128: "https://i.ibb.co/B7CpjJ8/Gxov-Yf5b-AAAA8x-C.jpg",
    anh129: "https://i.ibb.co/4Z08qRhd/Gxowo2eb-QAADCRP.jpg",
    anh130: "https://i.ibb.co/hF31x7tm/Gxoxy-XAbo-AAz-U8z.jpg",
    anh131: "https://i.ibb.co/DDjkGQYG/Gxoy91-Raw-AAg-IIk.jpg",
    anh132: "https://i.ibb.co/DHw8rQNd/Gxp-FQUaaw-AAIfrg.jpg",
    anh133: "https://i.ibb.co/FLvFD0g3/Gxpu-HZOaw-AEWbrh.jpg",
    anh134: "https://i.ibb.co/6RvVBbSP/Gxqnp-DIaw-AU6-G4-I-1.jpg",
    anh135: "https://i.ibb.co/NgMQC36z/Gxqnp-DIaw-AU6-G4-I.jpg",
    anh136: "https://i.ibb.co/wFzxrJRR/Gxq-V8-jb-MAAl-V-x.jpg",
    anh137: "https://i.ibb.co/sJ57VwJy/Gxq-Wa-Hdaw-AAPv-Ya.jpg",
    anh138: "https://i.ibb.co/LdjvMDkx/Gx-R4-NYoag-AAs-Xb8.png",
    anh139: "https://i.ibb.co/0RVvMv0v/Gxra7-Njb-AAAHqm-Z.jpg",
    anh140: "https://i.ibb.co/Fbqh2ZdZ/Gxrl19nb-YAA-00j.jpg",
    anh141: "https://i.ibb.co/GQNZYbyN/Gxr-N3-J9aw-AExu-KC.jpg",
    anh142: "https://i.ibb.co/SDdLb1sm/Gxr-O0-DOa8-AA-BMf.jpg",
    anh143: "https://i.ibb.co/zhNzVcjS/Gxr-OEscaw-AIDk-Aa.jpg",
    anh144: "https://i.ibb.co/zVPJKmJL/Gxr-Omgbak-AAk8-St.jpg",
    anh145: "https://i.ibb.co/JjLhZphC/Gxrsyiea-YAAcry5.jpg",
    anh146: "https://i.ibb.co/KxD98xS6/Gxrv-E-9aw-AMfn9-Z.jpg",
    anh147: "https://i.ibb.co/7dfDcnS9/Gx-Rw-MDja-IAAnkj4.jpg",
    anh148: "https://i.ibb.co/fzbFxHFf/Gx-SASTWa-EAADg-V5.jpg",
    anh149: "https://i.ibb.co/S7s9FPvn/Gx-SFt-AGa-IAIfg-Iz.jpg",
    anh150: "https://i.ibb.co/CKmHLNR5/Gx-SHP63a-IAE6-LGv.jpg",
    anh151: "https://i.ibb.co/BKqPmVQR/Gxs-Si-GKa-AAAii-AR.jpg",
    anh152: "https://i.ibb.co/whNzBNBM/Gx-STb-P5b-QAAwi-XN.jpg",
    anh153: "https://i.ibb.co/Kpb3z7gM/Gxs-Ui-G6aw-AAg-TON.jpg",
    anh154: "https://i.ibb.co/gb2cCJGN/Gxs-Vz-JLa-AAAdo1-X.jpg",
    anh155: "https://i.ibb.co/gM69x9hh/Gxs-W9dnaw-AAdeyf.jpg",
    anh156: "https://i.ibb.co/TD6t13PP/Gxs-Ww6-WWYAAO4-YA.jpg",
    anh157: "https://i.ibb.co/KxD98xS6/Gxrv-E-9aw-AMfn9-Z.jpg",
    anh158: "https://i.ibb.co/nNY450h4/Gxs-ZX36aw-AIe-Kv-Y.jpg",
    anh159: "https://i.ibb.co/pjG3Zbzg/Gxt-2-Zba4-AAX8k-X.jpg",
    anh160: "https://i.ibb.co/cKrWvjmn/Gxt2-CNpbs-AELa-OZ-1.jpg",
    anh161: "https://i.ibb.co/NwH1zsy/Gxt2-CNpbs-AELa-OZ.jpg",
    anh162: "https://i.ibb.co/SXv75LBw/Gxt7x9-Zaw-AAABFz.jpg",
    anh163: "https://i.ibb.co/MxCNMGMJ/Gxm-U6-Qcb-IAAcob-D.jpg",
    anh164: "https://i.ibb.co/HLW4s6XX/Gxtfy-YWbc-AA6-UBW.jpg",
    anh165: "https://i.ibb.co/272HfF8y/Gxth-WBAb-YAAChu-J.jpg",
    anh166: "https://i.ibb.co/vvq0KF6X/Gxti-JZaw-AEMB-m-1.jpg",
    anh167: "https://i.ibb.co/JRc9hpwX/Gxti-JZaw-AEMB-m.jpg",
    anh168: "https://i.ibb.co/3yCmLRnk/Gxtj-HO5bk-AARa7-Z.jpg",
    anh169: "https://i.ibb.co/rK7RfxKM/Gxt-k-Aeas-AAajbq.jpg",
    anh170: "https://i.ibb.co/8nv05vZk/Gxtk-N-Iaw-AU3-tb.jpg",
    anh171: "https://i.ibb.co/VcmGTJbB/Gxn2-Q7-Gaw-AApk-Tp.jpg",
    anh172: "https://i.ibb.co/5X01SmCc/Gxoiu-A7aw-AEWft7.jpg",
    anh173: "https://i.ibb.co/jvc6jnjv/Gxu0zt-Oac-AAx-S-N.jpg",
    anh174: "https://i.ibb.co/Y4B0146B/Gxu2-Acdaw-AEl2-JT.jpg",
    anh175: "https://i.ibb.co/bgpjFhqX/Gxu3-JKIb-UAAn9-RG.jpg",
    anh176: "https://i.ibb.co/3YC6rZDp/Gxu4-VWvaw-AIm-h-F.jpg",
    anh177: "https://i.ibb.co/pjXrYSZ1/Gxu5fz-Ga-QAAQc-Kj.jpg",
    anh178: "https://i.ibb.co/XrT46WyR/Gxu7b-GJXAAAua-C0.jpg",
    anh179: "https://i.ibb.co/pB7KFF4s/Gxu-BOJpaw-AIQPpl.jpg",
    anh180: "https://i.ibb.co/FkJxMX66/Gxu-Ccb-Tb-MAApv-Xk.jpg",
    anh181: "https://i.ibb.co/mrWp2pYZ/Gxu-D6ujaw-AE-os-V.jpg",
    anh182: "https://i.ibb.co/8LpH925r/Gxuks9-Baw-AM-Fp-U.jpg",
    anh183: "https://i.ibb.co/VYHqj1cm/Gxn-AN0kaw-AA2-MRw.jpg",
    anh184: "https://i.ibb.co/hxx2SL6T/Gxu-Mz-Faw-AApj0d.jpg",
    anh185: "https://i.ibb.co/vvkG2pPW/Gxunss7aw-AEIC0-U.jpg",
    anh186: "https://i.ibb.co/Psd5tJg7/Gxu-Nx-Jjaw-AAAb-Dy.jpg",
    anh187: "https://i.ibb.co/hJzdNczp/Gxuoel-Uaw-AE7e-ZT.jpg",
    anh188: "https://i.ibb.co/ZzBV1yt0/Gxupr3gaw-AAoqt7.jpg",
    anh189: "https://i.ibb.co/JRNcMv26/Gxuq8f-Vaw-AICTZS.jpg",
    anh190: "https://i.ibb.co/CKDWfJVc/Gxur5-Z2aw-AEe-Lin-1.jpg",
    anh191: "https://i.ibb.co/XxZx8Hg0/Gxur5-Z2aw-AEe-Lin.jpg",
    anh192: "https://i.ibb.co/KcZ5MTvq/Gxus-It-Paw-AM-vdo.jpg",
    anh193: "https://i.ibb.co/xSDjqKDr/Gxu-TA8-Eaw-AE-o-Im.jpg",
    anh194: "https://i.ibb.co/TMcR913H/Gxutm-XYaw-AEqqu-Z.jpg",
    anh195: "https://i.ibb.co/XxT8qGLH/Gxuy-FPGak-AAok-Uz.jpg",
    anh196: "https://i.ibb.co/4gJnKNGm/Gxuzi4caw-AEk3-Cy.jpg",
    anh197: "https://i.ibb.co/0yj0xZqz/Gxv-Fcqa-YAArnw9.jpg",
    anh198: "https://i.ibb.co/zWv5SFsh/Gxv2z1na-QAAx-Zn4.jpg",
    anh199: "https://i.ibb.co/n848VSQQ/Gxv3-QIda4-AEg-Si-Q.jpg",
    anh200: "https://i.ibb.co/V0cGg5mz/Gxv3-UUra-EAACQdc.jpg",
    anh201: "https://i.ibb.co/v4Fpt4RT/Gxv6b-L2a-YAArx-Ad.jpg",
    anh202: "https://i.ibb.co/SXMK8cCW/Gxv-8lta0-AAyj3k.jpg",
    anh203: "https://i.ibb.co/WWWz7SyL/Gxv8nf-Tbk-AAcl-UG.jpg",
    anh204: "https://i.ibb.co/PsFzjp3b/Gxv9-j-Pb-MAA-xzi.jpg",
    anh205: "https://i.ibb.co/VW5dJLmd/Gxv24-Gdb-YAAFe-Cx.jpg",
    anh206: "https://i.ibb.co/LXrxs5QC/Gxv52k-a4-AAd1rc.jpg",
    anh207: "https://i.ibb.co/XrnK34tk/Gx-VCV5-Qa-IAMo-NRX.jpg",
    anh208: "https://i.ibb.co/M51B5zFW/Gxv-DOP3-WMAAArk2.jpg",
    anh209: "https://i.ibb.co/p72wmCH/Gxvf5nla-UAAcwi-T.jpg",
    anh210: "https://i.ibb.co/jkqmZ2Rr/Gxvfmw-La-QAAD3-EQ.jpg",
    anh211: "https://i.ibb.co/jZw3Xpst/Gxvfrkba-AAABeb-D.jpg",
    anh212: "https://i.ibb.co/tMcTW8Gr/Gxvf-RUEb0-AATsp-E.jpg",
    anh213: "https://i.ibb.co/chx9t3VF/Gxvf-XCGa-MAAa8e-V.jpg",
    anh214: "https://i.ibb.co/ksVtx0QM/Gxvgd-K5a-IAALg4-O.jpg",
    anh215: "https://i.ibb.co/Hp1Ygx1B/Gxvg-KRqbs-AAh-Vx-Z.jpg",
    anh216: "https://i.ibb.co/VYKNYPRB/Gxvi-G21bk-AEZ8dw.jpg",
    anh217: "https://i.ibb.co/WN4zgxYT/Gxvi-Zs-Dac-AA-az5.jpg",
    anh218: "https://i.ibb.co/MDhHrnH5/Gxvjs-ZGbk-AAOSy-Z.jpg",
    anh219: "https://i.ibb.co/n8BhcMfX/Gxvj-Wv-Oa8-AAgh-My.jpg",
    anh220: "https://i.ibb.co/cKDLtwvF/Gxvjz-A5b-MAACxn-U.jpg",
    anh221: "https://i.ibb.co/p6yfRMVz/Gxvk-6oa-IAAVRc7.jpg",
    anh222: "https://i.ibb.co/Qvb0fmv4/Gxvk-DWUa-MAA8-QAa.jpg",
    anh223: "https://i.ibb.co/ZpbbsrXc/Gxvkk-Tybo-AEm-Vc-D.jpg",
    anh224: "https://i.ibb.co/zV5WgfY5/Gxvkl2mbw-AA9-Tlz.jpg",
    anh225: "https://i.ibb.co/XxJT5jsq/Gxvl51-Ib-EAAEkuw.jpg",
    anh226: "https://i.ibb.co/C3VvTmWB/Gxvm570b-AAAIy-PG.jpg",
    anh227: "https://i.ibb.co/Vpk2p952/Gxvm-OBkb-MAAOe-YL.jpg",
    anh228: "https://i.ibb.co/chXxHd2d/Gxv-MTXmbk-AAx-Ott.jpg",
    anh229: "https://i.ibb.co/GQKfg779/Gxvm-U0za-MAA2v-W4.jpg",
    anh230: "https://i.ibb.co/ds7H7404/Gxv-Ndq-Kbg-AA-GBA.jpg",
    anh231: "https://i.ibb.co/FbvcLBHF/Gxvnqt-Wa-IAAUS4-A.jpg",
    anh232: "https://i.ibb.co/jv15rMxn/Gxvobshb0-AAg7-ZN.jpg",
    anh233: "https://i.ibb.co/7xZnXkQc/Gxv-Q7-Osas-AAdx5-V.jpg",
    anh234: "https://i.ibb.co/4n6n1JjD/Gxvr-KGsb-MAAvo-A.jpg",
    anh235: "https://i.ibb.co/SwHh9c7p/Gxvs-Etfb-QAAEz-GT.jpg",
    anh236: "https://i.ibb.co/4R8MZ0X9/Gxvs-Njwbw-AArz-Ij.jpg",
    anh237: "https://i.ibb.co/6c9yRTNK/Gxv-TCQsa-YAAECCJ.jpg",
    anh238: "https://i.ibb.co/XrPK3TTt/Gxv-Tgkd-Xs-AA0-S6x.jpg",
    anh239: "https://i.ibb.co/Fq0Zpd3G/Gxv-TYvf-XYAACi1l-1.jpg",
    anh240: "https://i.ibb.co/99NqkMRN/Gxv-TYvf-XYAACi1l.jpg",
    anh241: "https://i.ibb.co/vvQ58HVD/Gxv-U5-Blag-AAdz-HQ.jpg",
    anh242: "https://i.ibb.co/rf312LmG/Gxvu-Gn-Gb-QAAPe-Pz.jpg",
    anh243: "https://i.ibb.co/N2VmmTrH/Gxvu-UXdbk-AAMMk-Z.jpg",
    anh244: "https://i.ibb.co/ycC1DqZd/Gxvuvh-Vb-EAAz-A5-F.jpg",
    anh245: "https://i.ibb.co/DDZWm8Fq/Gx-Vv9-TCbc-AAX1-s.jpg",
    anh246: "https://i.ibb.co/gLvt0QZn/Gxvv78-Lbc-AANWI2.jpg",
    anh247: "https://i.ibb.co/pNzs345/Gxvvfl5ao-AAWB7-A.jpg",
    anh248: "https://i.ibb.co/nH5PJSN/Gxvv-WP4b-MAA21bt.jpg",
    anh249: "https://i.ibb.co/4ZtDJmBx/Gxvw6j-ZWc-AAg-SF0.jpg",
    anh250: "https://i.ibb.co/kv4s8PD/Gxvw-WBvbc-AArqgq.jpg",
    anh251: "https://i.ibb.co/chh6gtR8/Gxvx-NVHb0-AA6-LBh.jpg",
    anh252: "https://i.ibb.co/d0VGy6Ty/Gxvxwmp-WAAAPYhu.jpg",
    anh253: "https://i.ibb.co/TBNgksgd/Gxvy3-Jf-Wg-AExd1b.jpg",
    anh254: "https://i.ibb.co/VYNzpLyC/Gxw-6-OLb-AAAau-BD.jpg",
    anh255: "https://i.ibb.co/0RFd5f35/Gxw-yo7bs-AAtk50.jpg",
    anh256: "https://i.ibb.co/fdwp6bzH/Gxw0-RV9a4-AAHv8-Q.jpg",
    anh257: "https://i.ibb.co/fGMLFsLF/Gxw1l-A-a0-AA84-Nt.jpg",
    anh258: "https://i.ibb.co/vvsLkB4g/Gx-W1ma-Dbo-AAo-I5b.jpg",
    anh259: "https://i.ibb.co/vxwFryg5/Gxw2-hkbs-AEbp1v.jpg",
    anh260: "https://i.ibb.co/MD1Y2qwf/Gxw-3-CEWMAALz-Ms.jpg",
    anh261: "https://i.ibb.co/nN8MnfXM/Gxw-3-Ct-XEAEPZi8.jpg",
    anh262: "https://i.ibb.co/v4x4Kqkz/Gx-W4x5tb-IAABMt-O.jpg",
    anh263: "https://i.ibb.co/c4x9vnS/Gxw5-Gstbs-AEoqy9.jpg",
    anh264: "https://i.ibb.co/99rKJRt9/Gxw7-J0ubs-AIr-Obc.jpg",
    anh265: "https://i.ibb.co/4nphQFyr/Gx-W8-WL1b-QAAz-DJH.jpg",
    anh266: "https://i.ibb.co/RGSgNd8t/Gxw9-LYUa4-AA3v-MH.jpg",
    anh267: "https://i.ibb.co/Psq1dcZR/Gxw720nbs-AASjl-T.jpg",
    anh268: "https://i.ibb.co/Df09gRn2/Gxw857abk-AAhsg-Y.jpg",
    anh269: "https://i.ibb.co/Df0KMTGj/Gxw-ALcya-MAEI34-N.jpg",
    anh270: "https://i.ibb.co/5xWTzHMY/Gxw-At-Apa-YAAMiqi.jpg",
    anh271: "https://i.ibb.co/KxD98xS6/Gxrv-E-9aw-AMfn9-Z.jpg",
    anh272: "https://i.ibb.co/KpRhXp0D/Gxw-BHa-Yas-AAzsdr.jpg",
    anh273: "https://i.ibb.co/CsndGNHq/Gxw-Bh-Q8a-EAAy-Il-N.jpg",
    anh274: "https://i.ibb.co/RkfnmDNk/Gxwbm-Bzbw-AEQfr-J.jpg",
    anh275: "https://i.ibb.co/Mk7C1vF7/Gxw-Cn9-Gbk-AA-u-Uy.jpg",
    anh276: "https://i.ibb.co/kVfcRrw8/Gxw-Cp-UFak-AMy-Ds.jpg",
    anh277: "https://i.ibb.co/LDffh5wS/Gxw-D2eub-MAAJ-N8.jpg",
    anh278: "https://i.ibb.co/6pv9vTs/Gxwd-K0-a-EAEb-Ra-J.jpg",
    anh279: "https://i.ibb.co/DHyJxwNb/Gxmrw1-Jaw-AAD4c-Z.jpg",
    anh280: "https://i.ibb.co/FLPzjs3S/Gxwga-NPbs-AATb-NN.jpg",
    anh281: "https://i.ibb.co/pCvtdmz/Gxwg-Kz-Va-EAAa-Wy-T.jpg",
    anh282: "https://i.ibb.co/39hBTB2F/Gxwh2-Tyag-AAOi6n.jpg",
    anh283: "https://i.ibb.co/JwNWhVx0/Gxwjm-T8bg-AAEQNF.jpg",
    anh284: "https://i.ibb.co/rGSFPk4C/Gxw-Le-Bbbs-AAwcpf.jpg",
    anh285: "https://i.ibb.co/5XqnhvCw/Gxw-l-Jnbs-AMcpu8.jpg",
    anh286: "https://i.ibb.co/q3WHKYfk/Gxwm-Yfba-MAAATt-X.jpg",
    anh287: "https://i.ibb.co/HDxwfhYC/Gxwn0s-Obs-AASARO.jpg",
    anh288: "https://i.ibb.co/XZwHhDS7/Gxw-Ni-Lo-Xs-AAy-Bt4.jpg",
    anh289: "https://i.ibb.co/svfh16t2/Gxw-OTawb0-AAQn-J8.jpg",
    anh290: "https://i.ibb.co/vCqyCQg0/Gxm-XRMFa-UAAb-OVg.jpg",
    anh291: "https://i.ibb.co/vFYFK8z/Gxwqx3jbk-AAVdq-L.jpg",
    anh292: "https://i.ibb.co/MkwxSWCH/Gx-Wsiz-Bao-AEIaay.jpg",
    anh293: "https://i.ibb.co/hRMdkV8v/Gxws-PY8bg-AABHs.jpg",
    anh294: "https://i.ibb.co/tMbfRmZH/Gxbq-QE-aw-AABMD.jpg",
    anh295: "https://i.ibb.co/wN5DN5WY/Gxwuiowbc-AAv-K-W-1.jpg",
    anh296: "https://i.ibb.co/gbj1Ltxc/Gxwuiowbc-AAv-K-W.jpg",
    anh297: "https://i.ibb.co/S4Qf3BLB/Gxw-UJLgb0-AAl-Gk-W.jpg",
    anh298: "https://i.ibb.co/F4rK67dw/Gxwuo-Cyag-AAn-WLv.jpg",
    anh299: "https://i.ibb.co/gLMTqvxM/Gxw-Uq-DXbk-AAHYr-C.jpg",
    anh300: "https://i.ibb.co/VW7Gsjhf/Gxw-Va-Qkb0-AAg7w-H.jpg",
    anh301: "https://i.ibb.co/k2sF57T4/Gxl-Mc-Vbo-AA9a-Hm.jpg",
    anh302: "https://i.ibb.co/WpWbzs4Q/Gxcjt6-Mb-IAAFIJ.jpg",
    anh303: "https://i.ibb.co/PGqFZzz8/Gxwyb3-Gac-AAOC9w.jpg",
    anh304: "https://i.ibb.co/0RkynySy/Gxwz-AQag-AAv-Q9w.jpg",
    anh305: "https://i.ibb.co/vCH8nrqG/Gxx-Bf-bs-AMZg-Sq.jpg",
    anh306: "https://i.ibb.co/B2tnrxgv/Gxx-BL-Aa8-AAz9-Q.jpg",
    anh307: "https://i.ibb.co/pB7KFF4s/Gxu-BOJpaw-AIQPpl.jpg",
    anh308: "https://i.ibb.co/zVCPJ4rp/Gxx-CXj-Qbs-AMg-Ja-K.jpg",
    anh309: "https://i.ibb.co/qLjpRp3d/Gxx-DYMwbs-AUXJ3v.jpg",
    anh310: "https://i.ibb.co/TMrJSyNs/Gxx-ESZqbs-AQf2r-V.jpg",
    anh311: "https://i.ibb.co/pjG3Zbzg/Gxt-2-Zba4-AAX8k-X.jpg",
    anh312: "https://i.ibb.co/BKszN8h2/Gxx-Fxkma4-AAHl-YE.jpg",
    anh313: "https://i.ibb.co/fzWVVZwK/Gxx-HAAbbs-AEd-85.jpg",
    anh314: "https://i.ibb.co/9mwYnSqp/Gxx-IMd6ao-AAsq-FI.jpg",
    anh315: "https://i.ibb.co/m5wr9PRC/Gxx-La-JCbs-AIR10v.jpg",
    anh316: "https://i.ibb.co/8g5Fqfzk/Gxx-LNW3b-QAAQao-A.jpg",
    anh317: "https://i.ibb.co/ZpbbsrXc/Gxvkk-Tybo-AEm-Vc-D.jpg",
    anh318: "https://i.ibb.co/1W6gVb3/Gxx-OG5-Cbs-AEkax-N.jpg",
    anh319: "https://i.ibb.co/C5tLr2gr/Gx-Xogbta8-AA7-SPO.jpg",
    anh320: "https://i.ibb.co/FLvFD0g3/Gxpu-HZOaw-AEWbrh.jpg",
    anh321: "https://i.ibb.co/pj1kkZNL/Gxx-RFRsbk-AAz-Ye1.jpg",
    anh322: "https://i.ibb.co/YT33GmZ0/Gxx-Sy-W4bs-AMJYSQ.jpg",
    anh323: "https://i.ibb.co/hJQmsG14/Gxx-UKTTb0-AAYLKt.jpg",
    anh324: "https://i.ibb.co/9HL0SZ21/Gxx-VFx-Ebs-AEUW9x.jpg",
    anh325: "https://i.ibb.co/gFTmqd8w/Gx-XVTWTac-AA1a-X7.jpg",
    anh326: "https://i.ibb.co/whsP5scS/Gxx-X36-Qbs-AIml-9.jpg",
    anh327: "https://i.ibb.co/PGCS5fcN/Gxx-ZTf-Zbs-AQ65-BQ.jpg",
    anh328: "https://i.ibb.co/qVyXrz2/Gx-Y6-Wqr-W4-AA03-WY.jpg",
    anh329: "https://i.ibb.co/HTHgr4kw/Gxz2s-Un-Xo-AAIu8v.jpg",
    anh330: "https://i.ibb.co/YBZhBJKg/Gx-Z9-XSxao-AA1-Ups.jpg",
    anh331: "https://i.ibb.co/bMzmDtqK/Gx-Zb-Y87a-QAAX34-N.jpg",
    anh332: "https://i.ibb.co/GfDMgDPN/Gx-Zvihya-QAAMZGg.jpg",
  };

  const imageUrl = images[slug] || "https://i.ibb.co/GfDMgDPN/Gx-Zvihya-QAAMZGg.jpg";
  const title = `Amazing video`;
  const description = `Amazing video`;
  const url = `https://cdnvidey.space/${slug}`;

  const html = `
<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!-- Basic Meta -->
  <title>${title}</title>
  <meta name="description" content="${description}">
  
  <!-- Open Graph / Facebook -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="${url}">
  <meta property="og:title" content="${title}">
  <meta property="og:description" content="${description}">
  <meta property="og:image" content="${imageUrl}">
  <meta property="og:image:secure_url" content="${imageUrl}">
  <meta property="og:image:type" content="image/jpeg">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="${title}">
  
  <!-- Twitter -->
  <meta name="twitter:card" content="summary">
  <meta name="twitter:url" content="${url}">
  <meta name="twitter:title" content="${title}">
  <meta name="twitter:description" content="${description}">
  <meta name="twitter:image" content="${imageUrl}">
  <meta name="twitter:image:alt" content="${title}">
  
  <style>
    body {
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      background: #f5f5f5;
      font-family: Arial, sans-serif;
      color: #333;
      font-size: 18px;
    }
  </style>
</head>
<body>
  <div>Checking your location and redirecting...</div>
  
  <script>
    setTimeout(function() {
      window.location.href = '${redirectUrl}';
    }, 2000);
  </script>
</body>
</html>
  `;

  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.status(200).send(html);
}
